In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
import pandas as pd
import numpy as np

In [19]:
# Loading the dataset
data = pd.read_csv("/content/module_159_data.csv")
data.head()

,step_0,step_1,step_2,step_3,step_4,step_5,step_6,step_7,step_8,step_9,target
0,0.891606,0.005835,0.902900,0.370187,0.156339,0.472637,0.431836,0.770866,0.119194,0.188136,0
1,0.844764,0.780533,0.411477,0.078435,0.852747,0.542090,0.107046,0.610290,0.918214,0.258306,1
2,0.850518,0.787294,0.365670,0.089276,0.064969,0.713258,0.931587,0.770217,0.291395,0.885698,1
3,0.698502,0.680091,0.543954,0.685820,0.424197,0.839638,0.691607,0.389333,0.168020,0.282097,1
4,0.628251,0.717192,0.233884,0.596176,0.339106,0.695727,0.729802,0.470927,0.409624,0.884498,1


In [20]:
# seperating features and targets
x = data.drop(['target'], axis=1).values
y = data['target'].values
print(x.shape)
print(y.shape)
print(x)
print(y)

(2000, 10)
(2000,)
[[0.89160578 0.00583528 0.90289975 ... 0.77086577 0.11919438 0.18813586]
 [0.84476361 0.78053258 0.41147697 ... 0.6102905  0.91821414 0.25830632]
 [0.8505181  0.78729391 0.3656703  ... 0.77021719 0.29139527 0.88569794]
 ...
 [0.16297826 0.74119209 0.13569624 ... 0.63094566 0.38398059 0.39155282]
 [0.19657287 0.60995403 0.34011613 ... 0.48231804 0.54936354 0.98077684]
 [0.80356694 0.49248089 0.49075725 ... 0.9021697  0.2930661  0.70269603]]
[0 1 1 ... 0 1 1]


In [21]:
# reshaping x: from (2000,10) to (2000,10,1), to add the feature dimensions required by LSTM
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x.shape)

(2000, 10, 1)


In [22]:
# Building the model
model = Sequential([
    LSTM(32, input_shape=(10,1)),
    Dense(1, activation='sigmoid')
])
model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                   │ (None, 32)             │         4,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,385 (17.13 KB)

 Trainable params: 4,385 (17.13 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
# compiling
model. compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [24]:
# Training
model.fit(x, y, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.5169 - loss: 0.6829 - val_accuracy: 0.4325 - val_loss: 0.6862
Epoch 2/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6100 - loss: 0.6114 - val_accuracy: 0.8075 - val_loss: 0.5016
Epoch 3/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7894 - loss: 0.4390 - val_accuracy: 0.8100 - val_loss: 0.4644
Epoch 4/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8350 - loss: 0.3705 - val_accuracy: 0.8300 - val_loss: 0.3873
Epoch 5/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8487 - loss: 0.3373 - val_accuracy: 0.8375 - val_loss: 0.3573
Epoch 6/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8687 - loss: 0.3049 - val_accuracy: 0.8300 - val_loss: 0.3299
Epoch 7/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8719 - loss: 0.2873 - val_accuracy: 0.8450 - val_loss: 0.3094
Epoch 8/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8888 - loss: 0.2717 - val_accuracy: 0.8525 - val_loss

In [25]:
acc = model.evaluate(x,y, verbose=0)[1]
print(f"Accuracy: {acc:.4f}")

Accuracy: 0.9230
